clean code and review permissions

diff --git a/.github/workflows/build-and-test.yaml b/.github/workflows/build-and-test.yaml
--- a/.github/workflows/build-and-test.yaml
+++ b/.github/workflows/build-and-test.yaml
@@ -12,8 +12,9 @@ jobs:
     name: Build and Test Front-End Image
     runs-on: ubuntu-latest
     permissions:
-      contents: write
       issues: write
+      contents: read
+      pull-requests: write
     env:
       MYSQL_ROOT_PASSWORD: fake_password
       MYSQL_DATABASE: socksdb
@@ -31,7 +32,7 @@ jobs:
         uses: hoverkraft-tech/compose-action@v2.0.1
         with:
           compose-file: "./docker-compose.yaml"
-        continue-on-error: false  # Allows the workflow to continue even if this step fails
+        continue-on-error: false
 
       - name: Wait for Container Termination
         if: steps.docker-compose.outcome == 'success'
@@ -43,10 +44,10 @@ jobs:
           echo "Container front-end-user-sim-1 has terminated."
 
       - name: Get Logs from Load-Test Container
-        id: get-logs
+        id: logs
         if: steps.docker-compose.outcome == 'success'
         run: |
-          docker logs -f front-end-user-sim-1 &> user-sim.log || true  # Capture logs and handle errors gracefully
+          docker logs -f front-end-user-sim-1 &> logs.txt || true
 
       - name: Post Logs as PR Comment
         if: steps.docker-compose.outcome == 'success'
@@ -57,7 +58,7 @@ jobs:
             const fs = require('fs');
             let logOutput;
             try {
-              logOutput = fs.readFileSync('user-sim.log', 'utf8');
+              logOutput = fs.readFileSync('logs.txt', 'utf8');
             } catch (error) {
               logOutput = 'Unable to read logs.';
             }
@@ -80,5 +81,5 @@ jobs:
             });
 
       - name: Docker Logs Status
-        if: steps.get-logs.outcome == 'failure'
+        if: steps.logs.outcome == 'failure'
         run: exit 1
